# Generated by Django 5.2.4 on 2025-07-27 06:41

import AI_chat_bot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_alter_list_api_key_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatBotQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "API_Key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.list_api_key",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_doc",
                    models.FileField(
                        upload_to=AI_chat_bot.models.get_upload_path,
                        validators=[AI_chat_bot.models.validate_pdf],
                    ),
                ),
                (
                    "API_Key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.list_api_key",
                    ),
                ),
            ],
        ),
    ]
