# Generated by Django 4.2.18 on 2025-01-18 06:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_api_key",
            name="key",
            field=models.CharField(
                default=accounts.models.List_API_Key.generate_uuid,
                max_length=255,
                unique=True,
            ),
        ),
    ]
