# Generated by Django 4.2.18 on 2025-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_list_api_key_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_api_key",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
