# Generated by Django 4.2.18 on 2025-01-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_list_api_key_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_api_key",
            name="name_service",
            field=models.CharField(max_length=255),
        ),
    ]
