# Generated by Django 5.1.8 on 2025-04-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_list_api_key_name_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_api_key",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
