# Generated by Django 4.2.18 on 2025-01-21 07:56

import FashinClipRecommendation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FashinClipRecommendation", "0003_rename_api_imagecollection_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagecollection",
            name="Processor_embedded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="agegroup",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="imagecollection",
            name="Photo",
            field=models.ImageField(
                upload_to="get_upload_path",
                validators=[FashinClipRecommendation.models.validate_image_format],
            ),
        ),
        migrations.AlterField(
            model_name="styles",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
