# Generated by Django 4.2.18 on 2025-01-22 14:27

import FashinClipRecommendation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "FashinClipRecommendation",
            "0005_remove_imagecollection_processor_embedded_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="imagecollection",
            name="Processor_embedded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="imagecollection",
            name="Photo",
            field=models.ImageField(
                upload_to=FashinClipRecommendation.models.get_upload_path,
                validators=[FashinClipRecommendation.models.validate_image_format],
            ),
        ),
        migrations.DeleteModel(
            name="preprocess_embedding",
        ),
    ]
