# Generated by Django 4.2.18 on 2025-02-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FashinClipRecommendation", "0007_prompt_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt_api",
            name="number_recommended_images",
            field=models.IntegerField(default=0),
        ),
    ]
