# Generated by Django 4.2.18 on 2025-02-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_alter_list_api_key_name_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "manual",
                    models.FileField(blank=True, null=True, upload_to="manuals/"),
                ),
                (
                    "API_KEY",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.list_api_key",
                    ),
                ),
            ],
        ),
    ]
