# Generated by Django 5.1.8 on 2025-04-13 08:51

import customized_RAG.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customized_RAG", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="name_file",
        ),
        migrations.RemoveField(
            model_name="product",
            name="manual",
        ),
        migrations.AddField(
            model_name="product",
            name="Processing_boolean",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="manual_file",
            field=models.FileField(
                default=datetime.datetime(
                    2025, 4, 13, 8, 51, 29, 759254, tzinfo=datetime.timezone.utc
                ),
                upload_to=customized_RAG.models.get_upload_path,
            ),
            preserve_default=False,
        ),
    ]
