# Generated by Django 5.1.8 on 2025-04-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "customized_RAG",
            "0002_rename_name_product_name_file_remove_product_manual_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="API_KEY",
            new_name="api_key",
        ),
    ]
