# Generated by Django 5.1.8 on 2025-04-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customized_RAG", "0003_rename_api_key_product_api_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="api_key",
            new_name="APIKey",
        ),
    ]
