# Generated by Django 5.1.8 on 2025-04-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_list_api_key_id"),
        ("customized_RAG", "0004_rename_api_key_product_apikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("query_text", models.TextField()),
                ("response_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "APIKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.list_api_key",
                    ),
                ),
            ],
        ),
    ]
