# Generated by Django 5.1.8 on 2025-04-21 06:27

import customized_RAG.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customized_RAG", "0005_query"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="response_text",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=customized_RAG.models.get_upload_path_response,
            ),
        ),
    ]
