# Generated by Django 5.1.8 on 2025-04-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customized_RAG", "0006_alter_query_response_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="query",
            old_name="response_text",
            new_name="response_image",
        ),
    ]
