# Generated by Django 4.2.18 on 2025-01-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_list_api_key_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                ("AgeGroupId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("CategoryId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="styles",
            fields=[
                ("StyleId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ImageCollection",
            fields=[
                ("ImageID", models.AutoField(primary_key=True, serialize=False)),
                ("Photo", models.ImageField(upload_to="get_upload_path")),
                (
                    "API",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.list_api_key",
                    ),
                ),
            ],
        ),
    ]
