# Generated by Django 4.2.18 on 2025-01-18 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fashin_clip_recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagecollection",
            name="AgeGroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fashin_clip_recommendations.agegroup",
            ),
        ),
        migrations.AddField(
            model_name="imagecollection",
            name="Category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fashin_clip_recommendations.category",
            ),
        ),
        migrations.AddField(
            model_name="imagecollection",
            name="Styles",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fashin_clip_recommendations.styles",
            ),
        ),
        migrations.AddField(
            model_name="imagecollection",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagecollection",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
