# Generated by Django 4.2.18 on 2025-01-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fashin_clip_recommendations",
            "0002_imagecollection_agegroup_imagecollection_category_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagecollection",
            old_name="API",
            new_name="APIKey",
        ),
    ]
