# Generated by Django 4.2.18 on 2025-01-21 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "fashin_clip_recommendations",
            "0004_imagecollection_processor_embedded_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagecollection",
            name="Processor_embedded",
        ),
        migrations.CreateModel(
            name="preprocess_embedding",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Processor_embedded", models.BooleanField(default=False)),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashin_clip_recommendations.imagecollection",
                    ),
                ),
            ],
        ),
    ]
