# Generated by Django 4.2.18 on 2025-02-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_list_api_key_name_service"),
        (
            "fashin_clip_recommendations",
            "0006_imagecollection_processor_embedded_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt_API",
            fields=[
                ("PromptID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "prompt",
                    models.TextField(
                        help_text="Enter the prompt text here", verbose_name="Prompt"
                    ),
                ),
                (
                    "APIKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.list_api_key",
                    ),
                ),
            ],
        ),
    ]
